### ISSUE TITLE
Lock down wallet keyfile with tighter permissions

### ISSUE THREAD

**Issue by shoenseiwaso** [kinfoundation/kin-sdk-python#12]
https://github.com/kinfoundation/kin-sdk-python/blob/a392a8e099a07f47b10861b63db416301d418f71/kin/sdk.py#L578

Could use os.fdopen(), something like this:
https://stackoverflow.com/questions/5624359/write-file-with-specific-permissions-in-python

**Comment by bolshoy** [comment]
@shoenseiwaso thank you for the suggestion, it has been implemented in another repo. This repo will soon be refactored to use erc20token.

**Comment by shoenseiwaso** [comment]
Great to hear, thanks for the note. I'll close the issue.
